#!/bin/bash
###                                           ###
###           g16 run script                  ###
###         modfied for cogef                 ###
# --------------------------------------------- #
#
# Problems: Christian.wick@fau.de
# Version: 1.0.0
# --------------------------------------------- #

# run_cogef.py will call cogef_rung16 (this file) with the gaussian.com file
# as first argument. it expects a gaussian.log file as output.
# make sure that run_cogef.py is visible in your path when executing run_cogef.sh.

# adjust these lines to your needs (e.g. you could also call another script 
# that takes care about the gaussian calculation - helpful on some computing clusters etc.)

# RunGauss
logfile="${1%.com}.log"
$g16root/g16/g16 < $1 > $logfile




